version: '3.5'
services:
  app :
    build:
      context: .
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - TWINE_USERNAME
      - TWINE_PASSWORD
      - DJANGO_SETTINGS_MODULE=tests.django_settings
